version: 2.1

workflows:
  build:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - circle_ci_jerem
  build-test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm test