version: 2.1

workflows:
  build-test:
    filters:
      branches:
        only:
          - circle_ci_jerem
jobs:
  build-test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm test