version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

jobs:
  docker:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      # build the application image
      - run: docker build -t $DOCKER_USER/test_joke_app_circleci .

      # deploy the image
      - run: docker push $DOCKER_USER/test_joke_app_circleci.

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circle_ci_jerem
                
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circle_ci_jerem

      - heroku/deploy-via-git:
          requires:
            - "node/run"
            - "node/test"
          app-name: "esgi-joke-app"
          filters:
            branches:
              only:
                - circle_ci_jerem