version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circle_ci_jerem
                
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circle_ci_jerem
  
  deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - "node/run"
            - "node/test"
          filters:
            branches:
              only:
                - circle_ci_jerem